name: Build AMI with Packer

on:
  push:
    tags:
      - "v*"

env:
  PRODUCT_VERSION: "latest"

jobs:

  packer:
    runs-on: ubuntu-latest
    name: Build AMI with Packer

    defaults:
      run:
        working-directory: packer

    env:
      AWS_ACCESS_KEY_ID       : ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_DEFAULT_REGION      : ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_SECRET_ACCESS_KEY   : ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: packer init worker.pkr.hcl

      - name: Run `packer validate`
        id: validate
        run: packer validate worker.pkr.hcl

      - name: Create variables JSON file for `packer build`
        run: |
          echo '{
            "APP_AWS_ACCESS_KEY_ID"     : "${{ secrets.APP_AWS_ACCESS_KEY_ID }}",
            "APP_AWS_SECRET_ACCESS_KEY" : "${{ secrets.APP_AWS_SECRET_ACCESS_KEY }}",
            "APP_AWS_DEFAULT_REGION"    : "${{ secrets.APP_AWS_DEFAULT_REGION }}",
            "APP_AWS_BUCKET_NAME"       : "${{ secrets.APP_AWS_BUCKET_NAME }}",
            "APP_AWS_SQS_QUEUE_URL"     : "${{ secrets.APP_AWS_SQS_QUEUE_URL }}",
            "APP_AWS_SNS_TOPIC_ARN"     : "${{ secrets.APP_AWS_SNS_TOPIC_ARN }}"
          }' > variables.json

      - name: Run `packer build`
        id: build
        run: packer build -var-file=variables.json -on-error=abort worker.pkr.hcl
